cookie:
  expiry_days: 30
  key: chave_secreta_aleatoria
  name: meu_app_cookie
credentials:
  usernames:
    adriano:
      email: adriano@email.com
      failed_login_attempts: 0
      logged_in: false
      name: Larilson
      password: $2b$12$FlmlQAc8bgeiWlwnVwAkDeY3dDED.co36olnqh0SaZ3uH038yakhG
      roles:
      - viewer
    joao:
      email: joao@email.com
      failed_login_attempts: 0
      logged_in: true
      name: joao Felipe
      password: $2b$12$9Kh4gdTlNBgRbZskXoMkTuMPFIuFVnQOZtiQKBV/eeZfpBhwOdVL2
      roles:
      - admin
    larilson:
      email: adriano@email.com
      failed_login_attempts: 0
      logged_in: false
      name: Larilson
      password: $2b$12$854kirsdlrc1DNTdGEgNwudRSjbkTygvLYmonn7Jkm5o8pKASe3US
      roles:
      - viewer
filiais:
  adriano: sao_jose
  joao: sao_jose
  larilson: sao_jose
