services:
  estoque:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:8501"
    volumes:
      - ${DATA_DIR}/DB:/DB
      - ${DATA_DIR}/config.yaml:/config.yaml
    restart: unless-stopped